language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
addons:
  postgresql: "9.6"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run db:reset
script:
  - npm run test
env:
  global:
    - PORT=6000
    - PUBLIC_URL=http://localhost:6000
    - SESSION_SECRET=asdfasdf
    - AUTO_LOGIN=true
    - GITHUB_LOGIN=orbiting
    - PUBLIC_ASSETS_URL=http://localhost:6000/assets
    - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
